=== commercetools/commercetools-api-reference/inlined/customer.schema.json
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "title":"Customer",
  "type":"object",
  "required":["id","version","email","firstName","lastName","password","addresses","isEmailVerified","createdAt","lastModifiedAt"],
  "properties":{
    "id":{
      "type":"string",
      "description":"The unique ID of this object"
    },
    "version":{
      "type":"number",
      "description":"The current version"
    },
    "customerNumber":{
      "type":"string",
      "description":"String that uniquely identifies a customer. It can be used to create more human-readable (in contrast to ID) identifier for the customer. It should be unique across a project. Once it's set it cannot be changed."
    },
    "createdAt":{
      "type":"string",
      "format":"date-time",
      "description":"Date of the creation"
    },
    "lastModifiedAt":{
      "type":"string",
      "format":"date-time",
      "description":"Date of last modification"
    },
    "email":{
      "type":"string"
    },
    "firstName":{
      "type":"string"
    },
    "lastName":{
      "type":"string"
    },
    "password":{
      "type":"string"
    },
    "middleName":{
      "type":"string"
    },
    "title":{
      "type":"string"
    },
    "dateOfBirth":{
      "type":"date"
    },
    "companyName":{
      "type":"string"
    },
    "addresses":{
      "type":"array",
      "items":{
        "title":"Address",
        "type":"object",
        "required":["country"],
        "properties":{
          "id":{
            "type":"string"
          },
          "title":{
            "type":"string"
          },
          "salutation":{
            "type":"string"
          },
          "firstName":{
            "type":"string"
          },
          "lastName":{
            "type":"string"
          },
          "streetName":{
            "type":"string"
          },
          "streetNumber":{
            "type":"string"
          },
          "additionalStreetInfo":{
            "type":"string"
          },
          "postalCode":{
            "type":"string"
          },
          "city":{
            "type":"string"
          },
          "region":{
            "type":"string"
          },
          "state":{
            "type":"string"
          },
          "country":{
            "type":"string",
            "description":"A two-digit country code as per <a href=\"http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2\">ISO 3166-1 alpha-2</a>."
          },
          "company":{
            "type":"string"
          },
          "department":{
            "type":"string"
          },
          "building":{
            "type":"string"
          },
          "apartment":{
            "type":"string"
          },
          "pOBox":{
            "type":"string"
          },
          "phone":{
            "type":"string"
          },
          "mobile":{
            "type":"string"
          },
          "email":{
            "type":"string"
          },
          "additionalAddressInfo":{
            "type":"string"
          }
        }
      }
    },
    "defaultShippingAddressId":{
      "type":"string"
    },
    "defaultBillingAddressId":{
      "type":"string"
    },
    "isEmailVerified":{
      "type":"boolean"
    },
    "externalId":{
      "type":"string"
    },
    "customerGroup":{
      "title":"Reference to a CustomerGroup",
      "description":"A `Reference` is a JSON object representing a (loose) reference to another resource on SPHERE.IO platform",
      "type":"object",
      "properties":{
        "typeId ":{
          "type":"string",
          "description":"The typeId designates the type of the referenced resource",
          "enum":["customerGroup"]
        },
        "id":{
          "type":"string",
          "description":"The unique ID of the referenced resource"
        }
      }
    }
  }
}

=== commercetools/commercetools-api-reference/examples/customer-update-response.example.json
{
    "addresses": [
        {
            "city": "Any City",
            "country": "US",
            "id": "some_456_id",
            "postalCode": "11111",
            "streetName": "Any Street",
            "streetNumber": "1337"
        }
    ],
    "email": "1-<random>@example.com",
    "firstName": "Jane",
    "id": "some_123_id",
    "isEmailVerified": false,
    "lastName": "Doe",
    "password": "secret123",
    "version": 4,
    "createdAt": "2015-05-06T12:10:12.421Z",
    "lastModifiedAt": "2015-07-06T13:22:33.339Z"
}
