=== commercetools/commercetools-api-reference/schemas/categories.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "title": "Categories List",
  "type": "object",

  "required": ["offset", "count", "total", "results"],

  "properties": {
    "offset": {
      "$ref": "schemas/offset.schema.json"
    },
    "count": {
      "$ref": "schemas/count.schema.json"
    },
    "total": {
      "$ref": "schemas/total.schema.json"
    },
    "results": {
      "type": "array",
      "items": {
        "$ref": "schemas/category.schema.json"
      }
    }
  }
}

=== commercetools/commercetools-api-reference/examples/custom-objects.example.json
{
  "offset": 0,
  "count": 2,
  "total": 2,
  "results": [
    {
      "id": "f584ebbb-3805-43f3-80c8-76f98b2c18b5",
      "version": 5,
      "container": "channel",
      "key": "ac390383-370f-43f8-a534-db1604cb96a8",
      "value": "{\"name\":\"Commercetools\",\"slug\":\"commercetools\",\"lat\":52.523753,\"lng\":13.380434}",
      "createdAt": "2015-05-28T09:48:35.098Z",
      "lastModifiedAt": "2015-07-01T15:58:36.930Z"
    },
    {
      "id": "d8523d32-a79d-441c-90f4-744cc342126e",
      "version": 2,
      "container": "test-container",
      "key": "test-key",
      "value": "test-value",
      "createdAt": "2016-02-18T10:36:29.468Z",
      "lastModifiedAt": "2016-02-18T10:36:29.571Z"
    }
  ]
}

=== commercetools/commercetools-api-reference/examples/states.example.json
{
  "offset": 0,
  "count": 2,
  "total": 2,
  "results": [
    {
      "id": "7c2e2694-aefe-43d7-888e-6a99514caaca",
      "version": 1,
      "key": "Initial",
      "type": "LineItemState",
      "roles": [],
      "name": {
        "en": "Initial"
      },
      "description": {
        "en": "Initial is the first that (custom) line item gets after it's creation"
      },
      "builtIn": true,
      "initial": true,
      "createdAt": "2015-01-21T09:22:03.906Z",
      "lastModifiedAt": "2015-01-21T09:22:03.906Z"
    },
    {
      "id": "fb2b1abd-7598-40f1-906c-9e5e7c6f8ebc",
      "version": 1,
      "key": "test-state",
      "type": "ProductState",
      "roles": [],
      "builtIn": false,
      "initial": true,
      "createdAt": "2016-02-18T17:18:53.338Z",
      "lastModifiedAt": "2016-02-18T17:18:53.338Z"
    }
  ]
}

=== commercetools/commercetools-api-reference/api-specs/ml/examples/image-search.json
{
  "count": 3,
  "offset": 0,
  "total": 110,
  "results": [
    {
      "imageUrl": "http://cdn6.bigcommerce.com/s-stm8v/products/586/images/1711/3D_GOLF_HOODIE_BLACK__17630.1481286168.490.588.jpg?c=2",
      "productVariants": [
        {
          "product": {
            "id": "0f5feac3-b50f-447b-8c36-7603153a2dd0",
            "typeId": "product"
          },
          "staged": true,
          "variantId": 1
        }
      ]
    },
    {
      "imageUrl": "http://images.koovscdn.com/uploads/products/81364_1a41bcd8e5e3a8bf675c48aa2be132a3_image1_zoom.jpg",
      "productVariants": [
        {
          "product": {
            "id": "8a7f5101-8b20-4ba6-8988-ff43dbf35d3d",
            "typeId": "product"
          },
          "staged": true,
          "variantId": 1
        }
      ]
    },
    {
      "imageUrl": "http://sandiegobrewing.com/gear/wp-content/uploads/2015/03/guy-white-380x380.png",
      "productVariants": [
        {
          "product": {
            "id": "15245f8f-478b-426a-b3a9-41e8257f39d9",
            "typeId": "product"
          },
          "staged": true,
          "variantId": 1
        },
        {
          "product": {
            "id": "a315869c-3d78-476c-99d1-3dec4375a97a",
            "typeId": "product"
          },
          "staged": false,
          "variantId": 1
        },
        {
          "product": {
            "id": "a315869c-3d78-476c-99d1-3dec4375a97a",
            "typeId": "product"
          },
          "staged": true,
          "variantId": 1
        }
      ]
    }
  ]
}
